const getBiggest = (e, r) => {},
  greeting = (e) => {},
  isTenOrFive = (e) => {},
  isInRange = (e) => {},
  isInteger = (e) => {},
  fizzBuzz = (e) => {},
  isPrime = (e) => {},
  returnFirst = (e) => {},
  returnLast = (e) => {},
  getArrayLength = (e) => {},
  incrementByOne = (e) => {},
  addItemToArray = (e, r) => {},
  addItemToFront = (e, r) => {},
  wordsToSentence = (e) => {},
  contains = (e, r) => {},
  addNumbers = (e) => {},
  averageTestScore = (e) => {},
  largestNumber = (e) => {};
module.exports = {
  getBiggest: getBiggest,
  greeting: greeting,
  isTenOrFive: isTenOrFive,
  isInRange: isInRange,
  isInteger: isInteger,
  fizzBuzz: fizzBuzz,
  isPrime: isPrime,
  returnFirst: returnFirst,
  returnLast: returnLast,
  getArrayLength: getArrayLength,
  incrementByOne: incrementByOne,
  addItemToArray: addItemToArray,
  addItemToFront: addItemToFront,
  wordsToSentence: wordsToSentence,
  contains: contains,
  addNumbers: addNumbers,
  averageTestScore: averageTestScore,
  largestNumber: largestNumber,
};
